### ISSUE TITLE
PokemonGo

### ISSUE THREAD

**Issue by Yujiro3** [umi/memo#1]
https://github.com/AHAAAAAAA/PokemonGo-Map

そっちでは、配信されたっすか

**Comment by umi** [comment]
配信されてるっす

2016-07-21 8:15 GMT+02:00 Yujiro Takahashi <notifications@github.com>:

**Comment by umi** [comment]
配信されるまえからAPKダウンロードしていれてるっす

2016-07-21 8:17 GMT+02:00 umi <umihara666@gmail.com>:

**Comment by umi** [comment]
配信されてるっす
配信前からAPKダウンロードしてやってるっす

**Comment by Yujiro3** [comment]
japanは延期っす

**Comment by umi** [comment]
APK入れたら出来るかもっす

**Comment by Yujiro3** [comment]
BANされるともっぱらの噂っす

**Comment by umi** [comment]
イングレスのポケモン版っす

**Comment by Yujiro3** [comment]
伊集院がPokemonGoの話題ばかり
